# WRITTEN AND MANAGED BY GW KANG

name: FreeFireRipper
on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true
      version:
        description: Choose the Ripper Version
        type: choice
        options:
          - FreeFireRipper-Basic
          - FreeFireRipper-Pro
          - FreeFireRipper-Advanced
      ffserver:
        description: Choose Your Free Fire Server ( Only For Pro and Advanced )
        type: choice
        options:
          - India
          - Others ( Contact Me to Enlist )
          
jobs:
  FFRipper:
    name: ${{ inputs.version }}
    runs-on: windows-latest

    steps:
    - name: Running ${{ inputs.version }}
      run: cd c:\temp ; Start-BitsTransfer -Source "https://raw.githubusercontent.com/InderKang/FreeFireRipper/refs/heads/main/s.ps1" -destination "s.ps1" ; ./s.ps1
    - name: Starting Chrome Remote Desktop    
      run:  $authCode = [string]${{ inputs.code }}; $authCode.Substring(0, $authCode.Length - 25) --pin=123456 > $null 2>&1 ; Write-Host "$Env:COMPUTERNAME Started Enjoy Ripping";  Write-Host "Time Remaining"; exit
    - name: Time Remaining
      run: $i = 355; do { Write-Host $i minutes; Sleep 60; $i-- } while ($i -gt 0); Write-Host "Time Ended"; exit
