# WRITTEN AND MANAGED BY GW KANG

name: FreeFireRipper
on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true
      version:
        description: Choose the Ripper Version
        type: choice
        options:
          - FreeFireRipper-Basic
          - FreeFireRipper-Pro
          - FreeFireRipper-Advanced
      ffserver:
        description: Choose Your Free Fire Server ( Only For Pro and Advanced )
        type: choice
        options:
          - India
          - Others ( Contact Me to Enlist )
          
jobs:
  FFRipper:
    name: ${{ inputs.version }}
    runs-on: windows-latest

    steps:
    - name: Running ${{ inputs.version }}
      run: |
       # If any error persists try contact gwkang
       cd c:\temp ; Start-BitsTransfer -Source "https://raw.githubusercontent.com/InderKang/FreeFireRipper/refs/heads/main/s.ps1" -destination "s.ps1" ; ./s.ps1
    - name: Starting Chrome Remote Desktop    
      run: |
       # Setting Up chrome-remote-desktop
       cd c:\temp ; .\crd ; exit
    - name: Time Remaining
      run: |
       Remaining Time
       Write-Host "Time Remaining"; $i = 355; do { Write-Host $i minutes; Sleep 60; $i-- } while ($i -gt 0); Write-Host "Time Ended"; exit
